import { config } from "dotenv";
import { resolve } from "path";
config({ path: resolve(__dirname, "..", ".env.local") });
import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import { contents } from "../drizzle/schema";

const DATABASE_URL = process.env.DATABASE_URL!;
const sql = neon(DATABASE_URL);
const db = drizzle(sql);

const SEED_DATA = [
  {
    contentNo: "MEE001",
    scene: "Meeting",
    cantoneseText: "你一阵 meeting 前，记得 update 返个 deck。",
    explanation: "提醒对方在开会前更新一下演示文稿。",
    mainKeyword: { word: "update", meaning: "更新", example: "Update the deck before the meeting." },
    supportKeywords: [{ word: "meeting", meaning: "会议" }, { word: "deck", meaning: "演示文稿 / PPT" }],
    tags: ["meeting", "update", "deck"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/001.mp3",
    isToday: true,
    sortOrder: 1,
  },
  {
    contentNo: "MEE002",
    scene: "Meeting",
    cantoneseText: "个个都 agree 咗个 timeline，唔好再改喇。",
    explanation: "大家都已经同意了时间安排，不要再改了。",
    mainKeyword: { word: "agree", meaning: "同意", example: "Everyone agreed on the timeline." },
    supportKeywords: [{ word: "timeline", meaning: "时间线 / 进度表" }],
    tags: ["meeting", "agree", "timeline"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/002.mp3",
    isToday: false,
    sortOrder: 2,
  },
  {
    contentNo: "MEE003",
    scene: "Meeting",
    cantoneseText: "不如你 summarize 返上个 meeting 讲咗咩重点。",
    explanation: "请你概述一下上次会议讲了什么重点。",
    mainKeyword: { word: "summarize", meaning: "总结 / 概述", example: "Can you summarize the key points?" },
    supportKeywords: [{ word: "meeting", meaning: "会议" }],
    tags: ["meeting", "summarize"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/003.mp3",
    isToday: false,
    sortOrder: 3,
  },
  {
    contentNo: "MEE004",
    scene: "Meeting",
    cantoneseText: "呢个 proposal 我冇 comment，可以直接 proceed。",
    explanation: "这份提案我没有意见，可以直接推进。",
    mainKeyword: { word: "proposal", meaning: "提案 / 建议书", example: "I have no comments on this proposal." },
    supportKeywords: [{ word: "comment", meaning: "意见" }, { word: "proceed", meaning: "继续进行" }],
    tags: ["meeting", "proposal", "comment"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/004.mp3",
    isToday: false,
    sortOrder: 4,
  },
  {
    contentNo: "MEE005",
    scene: "Meeting",
    cantoneseText: "我谂你需要 align 返同其他 team 先。",
    explanation: "我觉得你需要先和其他团队对接好。",
    mainKeyword: { word: "align", meaning: "对齐 / 协调", example: "You need to align with other teams first." },
    supportKeywords: [{ word: "team", meaning: "团队" }],
    tags: ["meeting", "align", "team"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/005.mp3",
    isToday: false,
    sortOrder: 5,
  },
  {
    contentNo: "FOL001",
    scene: "Follow up",
    cantoneseText: "麻烦你 follow up 返个 client 嘅 feedback。",
    explanation: "请你跟进一下客户的反馈。",
    mainKeyword: { word: "follow up", meaning: "跟进", example: "Please follow up on the client's feedback." },
    supportKeywords: [{ word: "client", meaning: "客户" }, { word: "feedback", meaning: "反馈" }],
    tags: ["follow-up", "client", "feedback"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/006.mp3",
    isToday: false,
    sortOrder: 6,
  },
  {
    contentNo: "FOL002",
    scene: "Follow up",
    cantoneseText: "个 deadline 就快到，帮我 chase 下佢哋。",
    explanation: "截止日期快到了，帮我去催促一下他们。",
    mainKeyword: { word: "chase", meaning: "催促 / 追", example: "Can you chase them for the update?" },
    supportKeywords: [{ word: "deadline", meaning: "截止日期" }],
    tags: ["follow-up", "chase", "deadline"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/007.mp3",
    isToday: false,
    sortOrder: 7,
  },
  {
    contentNo: "FOL003",
    scene: "Follow up",
    cantoneseText: "份 report 仲 pending 紧，等紧 legal team 嘅 approval。",
    explanation: "这份报告还在等待法律团队的审批。",
    mainKeyword: { word: "pending", meaning: "待定 / 等待中", example: "The report is still pending approval." },
    supportKeywords: [{ word: "report", meaning: "报告" }, { word: "approval", meaning: "审批" }],
    tags: ["follow-up", "pending", "report"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/008.mp3",
    isToday: false,
    sortOrder: 8,
  },
  {
    contentNo: "FOL004",
    scene: "Follow up",
    cantoneseText: "你 send 个 email 俾佢哋 confirm 返个 schedule。",
    explanation: "你发邮件给他们确认一下时间安排。",
    mainKeyword: { word: "confirm", meaning: "确认", example: "Please send an email to confirm the schedule." },
    supportKeywords: [{ word: "email", meaning: "电子邮件" }, { word: "schedule", meaning: "时间安排" }],
    tags: ["follow-up", "confirm", "email"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/009.mp3",
    isToday: false,
    sortOrder: 9,
  },
  {
    contentNo: "FOL005",
    scene: "Follow up",
    cantoneseText: "我琴日 send 咗个 reminder，但系仲未有人 reply。",
    explanation: "我昨天发了提醒，但还没人回复。",
    mainKeyword: { word: "reply", meaning: "回复", example: "No one replied to my reminder." },
    supportKeywords: [{ word: "reminder", meaning: "提醒" }],
    tags: ["follow-up", "reply", "reminder"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/010.mp3",
    isToday: false,
    sortOrder: 10,
  },
  {
    contentNo: "APP001",
    scene: "Approval",
    cantoneseText: "呢个 budget 要 manager approve 先可以 proceed。",
    explanation: "这个预算需要经理批准才能继续。",
    mainKeyword: { word: "approve", meaning: "批准", example: "The manager needs to approve the budget first." },
    supportKeywords: [{ word: "manager", meaning: "经理" }, { word: "budget", meaning: "预算" }],
    tags: ["approval", "approve", "manager"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/011.mp3",
    isToday: false,
    sortOrder: 11,
  },
  {
    contentNo: "APP002",
    scene: "Approval",
    cantoneseText: "份 contract 已经 review 过，等紧 final sign-off。",
    explanation: "合同已经审查过了，等待最终签字确认。",
    mainKeyword: { word: "review", meaning: "审查 / 复核", example: "The contract has been reviewed." },
    supportKeywords: [{ word: "contract", meaning: "合同" }, { word: "sign-off", meaning: "签字确认" }],
    tags: ["approval", "review", "contract"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/012.mp3",
    isToday: false,
    sortOrder: 12,
  },
  {
    contentNo: "APP003",
    scene: "Approval",
    cantoneseText: "你帮我 check 下呢个 request 嘅 status。",
    explanation: "你帮我查一下这个申请的状态。",
    mainKeyword: { word: "request", meaning: "申请 / 请求", example: "Can you check the status of this request?" },
    supportKeywords: [{ word: "status", meaning: "状态" }],
    tags: ["approval", "request", "status"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/013.mp3",
    isToday: false,
    sortOrder: 13,
  },
  {
    contentNo: "APP004",
    scene: "Approval",
    cantoneseText: "Director 话要 reconsider 个 proposal，可能要再改。",
    explanation: "总监说要重新考虑这个方案，可能还要再修改。",
    mainKeyword: { word: "reconsider", meaning: "重新考虑", example: "The director wants to reconsider the proposal." },
    supportKeywords: [{ word: "director", meaning: "总监" }, { word: "proposal", meaning: "提案" }],
    tags: ["approval", "reconsider", "director"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/014.mp3",
    isToday: false,
    sortOrder: 14,
  },
  {
    contentNo: "APP005",
    scene: "Approval",
    cantoneseText: "冇 senior 嘅 approval 唔好 release 住。",
    explanation: "没有高层的批准先不要发布。",
    mainKeyword: { word: "release", meaning: "发布 / 上线", example: "Don't release without senior approval." },
    supportKeywords: [{ word: "senior", meaning: "高级 / 上级" }, { word: "approval", meaning: "批准" }],
    tags: ["approval", "release", "senior"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/015.mp3",
    isToday: false,
    sortOrder: 15,
  },
  {
    contentNo: "CLI001",
    scene: "Client",
    cantoneseText: "个 client 对个 proposal 好满意，话想尽快 kick-off。",
    explanation: "客户对提案很满意，说想尽快启动项目。",
    mainKeyword: { word: "kick-off", meaning: "启动 / 开始", example: "The client wants to kick off as soon as possible." },
    supportKeywords: [{ word: "client", meaning: "客户" }, { word: "proposal", meaning: "提案" }],
    tags: ["client", "kick-off", "proposal"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/016.mp3",
    isToday: false,
    sortOrder: 16,
  },
  {
    contentNo: "CLI002",
    scene: "Client",
    cantoneseText: "个客话个 quotation 太贵，叫我哋 revise 下。",
    explanation: "客户说报价太贵了，让我们修改一下。",
    mainKeyword: { word: "quotation", meaning: "报价单", example: "The client asked us to revise the quotation." },
    supportKeywords: [{ word: "revise", meaning: "修改 / 调整" }],
    tags: ["client", "quotation", "revise"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/017.mp3",
    isToday: false,
    sortOrder: 17,
  },
  {
    contentNo: "CLI003",
    scene: "Client",
    cantoneseText: "同个 client present 之前，记得 rehearse 多几次。",
    explanation: "给客户演示之前，记得多排练几次。",
    mainKeyword: { word: "present", meaning: "演示 / 汇报", example: "Rehearse before you present to the client." },
    supportKeywords: [{ word: "rehearse", meaning: "排练" }, { word: "client", meaning: "客户" }],
    tags: ["client", "present", "rehearse"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/018.mp3",
    isToday: false,
    sortOrder: 18,
  },
  {
    contentNo: "CLI004",
    scene: "Client",
    cantoneseText: "个客嘅 expectation 好高，你 manage 住先。",
    explanation: "客户的期望值很高，你先稳住。",
    mainKeyword: { word: "expectation", meaning: "期望", example: "The client's expectations are very high." },
    supportKeywords: [{ word: "manage", meaning: "管理 / 处理" }],
    tags: ["client", "expectation", "manage"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/019.mp3",
    isToday: false,
    sortOrder: 19,
  },
  {
    contentNo: "CLI005",
    scene: "Client",
    cantoneseText: "个客想 extend 个 trial period 多一个月。",
    explanation: "客户想把试用期延长一个月。",
    mainKeyword: { word: "extend", meaning: "延长", example: "The client wants to extend the trial period." },
    supportKeywords: [{ word: "trial period", meaning: "试用期" }],
    tags: ["client", "extend", "trial"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/020.mp3",
    isToday: false,
    sortOrder: 20,
  },
  {
    contentNo: "TEA001",
    scene: "Teamwork",
    cantoneseText: "你放假前同我 handover 返啲 ongoing project 先。",
    explanation: "你休假之前先把进行中的项目交接给我。",
    mainKeyword: { word: "handover", meaning: "交接", example: "Please handover the ongoing projects before your leave." },
    supportKeywords: [{ word: "ongoing", meaning: "进行中的" }, { word: "project", meaning: "项目" }],
    tags: ["teamwork", "handover", "ongoing"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/021.mp3",
    isToday: false,
    sortOrder: 21,
  },
  {
    contentNo: "TEA002",
    scene: "Teamwork",
    cantoneseText: "你 briefing 下新同事，佢唔熟个 process。",
    explanation: "你给新同事做个简短说明，他不熟悉流程。",
    mainKeyword: { word: "briefing", meaning: "简报 / 说明", example: "Brief the new colleague on the process." },
    supportKeywords: [{ word: "process", meaning: "流程" }, { word: "colleague", meaning: "同事" }],
    tags: ["teamwork", "briefing", "process"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/022.mp3",
    isToday: false,
    sortOrder: 22,
  },
  {
    contentNo: "TEA003",
    scene: "Teamwork",
    cantoneseText: "呢单嘢我 handle 开，你唔使担心。",
    explanation: "这件事我在负责处理，你不用担心。",
    mainKeyword: { word: "handle", meaning: "处理 / 负责", example: "I'm handling this, don't worry." },
    supportKeywords: [],
    tags: ["teamwork", "handle"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/023.mp3",
    isToday: false,
    sortOrder: 23,
  },
  {
    contentNo: "TEA004",
    scene: "Teamwork",
    cantoneseText: "大家分工合作，你负责 research，我做 presentation。",
    explanation: "大家分工合作，你负责调研，我来做演示。",
    mainKeyword: { word: "research", meaning: "调研 / 研究", example: "You do the research and I'll do the presentation." },
    supportKeywords: [{ word: "presentation", meaning: "演示 / 汇报" }],
    tags: ["teamwork", "research", "presentation"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/024.mp3",
    isToday: false,
    sortOrder: 24,
  },
  {
    contentNo: "TEA005",
    scene: "Teamwork",
    cantoneseText: "你有咩 concern 可以 raise 出嚟，唔好收埋。",
    explanation: "你有什么顾虑可以提出来，不要藏着。",
    mainKeyword: { word: "concern", meaning: "顾虑 / 担忧", example: "Raise any concerns you may have." },
    supportKeywords: [{ word: "raise", meaning: "提出" }],
    tags: ["teamwork", "concern", "raise"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/025.mp3",
    isToday: false,
    sortOrder: 25,
  },
  {
    contentNo: "OTU001",
    scene: "OT / Urgent",
    cantoneseText: "今日 EOD 前要交，唔该帮帮手。",
    explanation: "今天下班前要交，请大家帮忙。",
    mainKeyword: { word: "EOD", meaning: "End of Day / 今日收工前", example: "Please submit by EOD." },
    supportKeywords: [],
    tags: ["urgent", "EOD"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/026.mp3",
    isToday: false,
    sortOrder: 26,
  },
  {
    contentNo: "OTU002",
    scene: "OT / Urgent",
    cantoneseText: "呢个 case 好 urgent，要 escalate 俾 senior management。",
    explanation: "这个情况非常紧急，需要上报给高级管理层。",
    mainKeyword: { word: "escalate", meaning: "升级上报", example: "We need to escalate this issue." },
    supportKeywords: [{ word: "urgent", meaning: "紧急的" }, { word: "case", meaning: "个案 / 情况" }],
    tags: ["urgent", "escalate"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/027.mp3",
    isToday: false,
    sortOrder: 27,
  },
  {
    contentNo: "OTU003",
    scene: "OT / Urgent",
    cantoneseText: "今晚要 OT 呀，个 deadline 听朝就到。",
    explanation: "今晚要加班，截止日期明天早上就到了。",
    mainKeyword: { word: "OT", meaning: "Overtime / 加班", example: "We need to OT tonight for the deadline." },
    supportKeywords: [{ word: "deadline", meaning: "截止日期" }],
    tags: ["urgent", "OT", "deadline"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/028.mp3",
    isToday: false,
    sortOrder: 28,
  },
  {
    contentNo: "OTU004",
    scene: "OT / Urgent",
    cantoneseText: "老细话呢个 task 系 top priority，其他嘢摆埋一边先。",
    explanation: "老板说这个任务是最高优先级，其他事情先放一边。",
    mainKeyword: { word: "priority", meaning: "优先级", example: "This task is top priority." },
    supportKeywords: [{ word: "task", meaning: "任务" }],
    tags: ["urgent", "priority", "task"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/029.mp3",
    isToday: false,
    sortOrder: 29,
  },
  {
    contentNo: "OTU005",
    scene: "OT / Urgent",
    cantoneseText: "个 system down 咗，要即刻 fix，唔系全公司做唔到嘢。",
    explanation: "系统宕机了，要马上修复，否则全公司无法工作。",
    mainKeyword: { word: "fix", meaning: "修复 / 解决", example: "The system is down, we need to fix it immediately." },
    supportKeywords: [{ word: "system", meaning: "系统" }],
    tags: ["urgent", "fix", "system"],
    reviewStatus: "published",
    audioStatus: "approved",
    audioUrl: "/audio/030.mp3",
    isToday: false,
    sortOrder: 30,
  },
];

async function seed() {
  console.log("Seeding database...");

  for (const item of SEED_DATA) {
    await db.insert(contents).values(item).onConflictDoNothing();
    console.log(`  Inserted: ${item.contentNo} — ${item.cantoneseText}`);
  }

  console.log(`\nDone! Seeded ${SEED_DATA.length} items.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
